<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '73a60399fae382fa5bcce81bdee607b7',
  'MYSQL_ROOT_PASSWORD' => 'password',
  'MYSQL_DATABASE' => 'drinksco',
  'MYSQL_USER' => 'user',
  'MYSQL_PASSWORD' => 'pass',
  'DATABASE_URL' => 'mysql://root:password@mysql:3306/drinksco?serverVersion=5.7',
);
