parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

imports:
    - { resource: context/sellers/services.yaml }
    - { resource: context/products/services.yaml }
    - { resource: context/carts/services.yaml }
